version: '2'
volumes:
  powerdns-db:
services:
  server:
    build: .
    ports:
      - '5300:53'
      - '5300:53/udp'
      - '8081:8081'
    environment:
      SOCKET_DIR: /var/run/pdns
    volumes:
      - powerdns-db:/var/lib/powerdns
      - /var/run/pdns:/var/run/pdns
